### ISSUE TITLE
The mod combination you selected is incorrectly defined!

### ISSUE THREAD

**Issue by Salm0nsnak3** [kingkarna1/fate-mod#1]
Trying to enable fate mod gives a Error: The Demon Hunters's unique "Receive free Great General when you discover Chilvary, Steel, Gunpowder" contains parameter Chilvary, Steel, Gunpowder, which does not fit parameter type tech! Warning: The Demon Hunters's unique "+45% Attacking Strength for cities" is deprecated as of 3.18.17, replace with "+45% Strength for cities "when attacking

**Comment by Salm0nsnak3** [comment]
Nvm i fixed it.

**Comment by kingkarna1** [comment]
woah  thx
